import React from 'react'

import Head from 'next/head'
import Hero from '@/components/AboutComponents/Hero'
import Mission from '@/components/AboutComponents/Mission'
import Choose from '@/components/AboutComponents/Choose'
import Plan from '@/components/AboutComponents/Plan'

const About = () => {
  return (
    
    <>
    <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/LOGO.jpg" />
      </Head>
    <Hero/>
    <Mission/>
    <Choose/>
    <Plan/>
    </>
  )
}

export default About