import Head from 'next/head'
import Image from 'next/image'

import styles from '@/styles/Home.module.css'
import Hero from '@/components/HomeComponents/Hero'
import Feature from '@/components/HomeComponents/Feature'
import AboutUs from '@/components/HomeComponents/AboutUs'
import Portfolio from '@/components/HomeComponents/Portfolio'
import Testimonials from '@/components/HomeComponents/Testimonial'
import Team from '@/components/HomeComponents/Team'
import ContactUs from '@/components/HomeComponents/ContactUs'



export default function Home() {
  
  return (
    <>
      <Head>
        <title>Care Services and Consultant LTD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/LOGO.jpg" />
      </Head>
      <main className={styles.main}>
      <Hero/>
      <Feature/>
      <AboutUs/>
      <Portfolio/>
      <Testimonials/>
      <Team/>
      <ContactUs/>
      
      </main>
    </>
  )
}
