import React from 'react'

import Head from 'next/head'
import Hero from '@/components/ServicesComponent/Hero'
import Specialities from '@/components/ServicesComponent/Specialities'
import Services from '@/components/ServicesComponent/Services'

const services = () => {
  return (
   <>
   <Head>
        <title>Service</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/LOGO.jpg" />
      </Head>
   <Hero/>
   <Specialities/>
   <Services/>
   </>
  )
}

export default services